package HarshCalcy;

/**
* HarshCalcy/CalculatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Sunday, October 19, 2014 5:50:27 PM PDT
*/

public final class CalculatorHolder implements org.omg.CORBA.portable.Streamable
{
  public HarshCalcy.Calculator value = null;

  public CalculatorHolder ()
  {
  }

  public CalculatorHolder (HarshCalcy.Calculator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HarshCalcy.CalculatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HarshCalcy.CalculatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HarshCalcy.CalculatorHelper.type ();
  }

}
