package HarshCalcy;


/**
* HarshCalcy/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Sunday, October 19, 2014 5:50:27 PM PDT
*/

public interface CalculatorOperations 
{
  int calculate (int _operator, int num1, int num2);
  void shutdown ();
} // interface CalculatorOperations
